name: Back up prod
on:
  workflow_dispatch:
#  schedule:
#    - cron: '59 23 * * *' # last minute of every day (UTC time zone)
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: backup/prod
      - name: Fetch db
        run: |
          chmod +x scripts/db-dump.sh \
            && ./scripts/db-dump.sh
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - name: Fetch uploads
        run: |
          chmod +x scripts/uploads-pull.sh \
            && ./scripts/uploads-pull.sh
        env:
          UPLOADS_DIR: ${{ secrets.UPLOADS_DIR }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: db public/uploads
          commit_message: Back up prod
          commit_user_name: Backup Bot
          commit_user_email: backup-bot@fake.com
          commit_author: Backup Bot <backup-bot@fake.com>
